// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: data.sql

package database

import (
	"context"
)

const insertData = `-- name: InsertData :exec
INSERT INTO data (url, content, created_at, updated_at) VALUES (
	?,
	?,
	datetime('now'),
	datetime('now')
)
`

type InsertDataParams struct {
	Url     string
	Content string
}

func (q *Queries) InsertData(ctx context.Context, arg InsertDataParams) error {
	_, err := q.db.ExecContext(ctx, insertData, arg.Url, arg.Content)
	return err
}
