// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Datum struct {
	ID        int64
	Url       string
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}
